version: '2.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
